# Generated by Django 3.2.13 on 2022-05-06 01:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='이메일')),
                ('realname', models.CharField(max_length=10, verbose_name='이름')),
                ('phonenum', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(regex='^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')], verbose_name='휴대폰 번호')),
                ('effcdate', models.DateField(verbose_name='입사 일자')),
                ('openingtime', models.TimeField(verbose_name='평소 근무 시작시간')),
                ('closingtime', models.TimeField(verbose_name='평소 근무 종료시간')),
                ('adminmemo', models.TextField(blank=True, max_length=1000, null=True, verbose_name='관리자 메모')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_mgr', models.BooleanField(default=False)),
                ('is_sbstt', models.BooleanField(default=False, verbose_name='연장근로 대체휴가 처리')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
