# Generated by Django 3.2.13 on 2022-05-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmthistory',
            name='closingtime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cmthistory',
            name='openingtime',
            field=models.TimeField(null=True),
        ),
    ]
