# Generated by Django 3.2.13 on 2022-05-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levhistory',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='levhistory',
            name='approval',
            field=models.CharField(choices=[('1', '대기'), ('2', '반려'), ('3', '승인')], default='1', max_length=1),
        ),
        migrations.DeleteModel(
            name='Annual',
        ),
    ]
